title: Fengcheng Wu
position: [Professor](https://physics.whu.edu.cn/info/1052/7001.htm) 
affiliation: School of Physics and Technology, Wuhan University
email: wufcheng@whu.edu.cn
google_scholar: https://scholar.google.com/citations?user=MIiCQ7wAAAAJ&hl=en
avatar: ./assets/img/photo.jpg
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
canonical: https://minimal-light.yyliu.net/
remote_theme: yaoyao-liu/minimal-light
