title: Fengcheng Wu
position: Professor
affiliation: School of Physics and Technology, Wuhan University
email: wufcheng@whu.edu.cn
google_scholar: https://scholar.google.com/citations?user=MIiCQ7wAAAAJ&hl=en
arXiv: https://arxiv.org/a/wu_f_1.html
publons: https://publons.com/researcher/1387914/fengcheng-wu/
avatar: ./assets/img/photo.jpg
favicon: ./assets/img/github.png
favicon_dark: ./assets/img/github.png
canonical: https://minimal-light.yyliu.net/
remote_theme: yaoyao-liu/minimal-light
